language: node_js
node_js:
    - "10"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: dukedev
  local_dir: dist/19.x
  on:
    branch: master
notifications:
  slack: dukeli:wKyuXwgTtAVE4NSCiUhocOYj